# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       hawaii-2048

# >> macros
# << macros

Summary:    2048 game
Version:    0.0.0.20140329.b459a11
Release:    1
Group:      Applications/System
License:    GPLv2+
URL:        https://github.com/mauios/hawaii-2048.git
Source0:    hawaii-2048-%{version}.tar.xz
Source100:  hawaii-2048.yaml
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Gui)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  cmake

%description
This is a highly addictive game where you use arrow keys to move
tiles in a 4x4 grid. When two tiles of the same number touch,
they merge into one.

If you get a tile with 2048 you win!


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
cd upstream
# << build pre

%cmake .  \
    -DCMAKE_BUILD_TYPE=RelWithDebInfo

make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
cd upstream
# << install pre
%make_install

# >> install post
# << install post

%files
%defattr(-,root,root,-)
%{_bindir}/hawaii-2048
%{_datadir}/hawaii-2048/styles/*
# >> files
# << files
